<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style type="text/css">
  
  
  
</style>
<body style="background: #009bff; 
    background: -webkit-linear-gradient(left, #0072ff, #00c6ff);height:350px;font-family: Helvetica, Arial, sans-serif;">

    <br><br><br><br><br><br>

<div class="container-fluid">
 
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <div class="col-sm-12" style="position:relative;width:80%;padding:3%;margin-left:10%;border-radius:10px;background-color:white;">
        <div class="col-sm-4">
            
            <img  src="img/mail/mail.png">
        </div>
        <div class="col-sm-8">
          <div class="col-sm-12">
            <div class="col-sm-2"></div>
            <div class="col-sm-8" style="margin-top:12%;">
              <p style="font-size:15px;font-weight:bold;text-align:center;">A NEW OPPORTUNITY WITH US</p>

              <p style="width:90%;margin-left:5%;background-color:#e6e6e6;padding:5px;border-radius:10px;font-weight:bold;">Name:</p>
              <p style="width:90%;margin-left:5%;background-color:#e6e6e6;padding:5px;border-radius:10px;font-weight:bold;">Subject:</p>
              <p style="width:90%;margin-left:5%;background-color:#e6e6e6;padding:5px;border-radius:10px;font-weight:bold;">Message:</p>
          </div>
            <div class="col-sm-2"></div>
          </div>
         
        </div>
        
      </div>
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>

</body>
</html>
